// packages/solid/src/types/index.ts
import type {
  LottieSource,
  RLottieDiagnostics,
  RLottieMetadata,
  RLottieQualitySnapshot,
  RLottieSeekTarget,
  RLottieStatus,
} from "@module-foundry/rlottie-web";
import type { Accessor } from "solid-js";

/** Return value of the SolidJS adapter. */
export interface CreateRLottieResult {
  canvasRef(element: HTMLCanvasElement): void;
  error: Accessor<Error | null>;
  metadata: Accessor<RLottieMetadata | null>;
  pause(): void;
  play(): void;
  quality: Accessor<RLottieQualitySnapshot>;
  seek(target: RLottieSeekTarget): void;
  start(source: LottieSource): Promise<RLottieMetadata>;
  status: Accessor<RLottieStatus>;
  stop(): void;
  /** Subscribe to windowed worker diagnostics without creating reactive frame updates. */
  subscribeDiagnostics(listener: (diagnostics: RLottieDiagnostics) => void): () => void;
}

// packages/react/src/types/index.ts
import type {
  LottieSource,
  RLottieDiagnostics,
  RLottieMetadata,
  RLottieSeekTarget,
  RLottieSnapshot,
} from "@module-foundry/rlottie-web";
import type { RefCallback } from "react";

/** Return value of the React adapter. */
export interface UseRLottieResult extends RLottieSnapshot {
  canvasRef: RefCallback<HTMLCanvasElement>;
  pause(this: void): void;
  play(this: void): void;
  seek(this: void, target: RLottieSeekTarget): void;
  start(this: void, source: LottieSource): Promise<RLottieMetadata>;
  stop(this: void): void;
  /** Subscribe to windowed worker diagnostics without causing frame-level React updates. */
  subscribeDiagnostics(this: void, listener: (diagnostics: RLottieDiagnostics) => void): () => void;
}
